name: "Plato Evaluator"
description: "Runs Plato Evaluations"
inputs:
  api-key:
    required: true
    type: string
    description: "Plato API key"
  base-url:
    required: false
    type: string
    description: "Base URL for the server"
    default: "https://plato.so"
  test-case-set-id:
    required: true
    type: number
    description: "Test case set ID"

runs:
  using: "node20"
  main: "dist/index.js"
outputs:
  batch-url:
    description: "URL to view the batch results"
    value: ${{ steps.plato.outputs.batchUrl }}
  batch-id:
    description: "ID of the batch run"
    value: ${{ steps.plato.outputs.batchId }}
  session-ids:
    description: "IDs of the individual test sessions"
    value: ${{ steps.plato.outputs.sessionIds }}
